<?php


?>

</br></br>
<?= $this->escapeHtml('<script>alert("zf")</script>'); ?>
</br></br>
<?= $this->escapeHtmlAttr("<script>alert('zf')</script>"); ?>
</br></br>
<?= $this->escapeJs('"bar"; alert("zf"); var xss="true"'); ?>
</br></br>
<?= $this->escapeCss("background-image: url('/zf.png?</style><script>alert(\'zf\')</script>');"); ?>
</br></br>
<?= $this->escapeUrl('/foo " onmouseover="alert(\'zf\')'); ?>
