<?php

/**
 * @var $messages array
 */

$form = $this->form;

$form->prepare();

$form->get('email')->setAttributes(
    [
        'class' => 'form-control',
        'placeholder' => 'name@example.com'
    ]
);

$form->get('body')->setAttributes(
    [
        'class' => 'form-control',
        'rows' => 7,
        'placeholder' => 'Напишите сюда ваше сообщение'
    ]
);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary mb-4']);

$filter = new \Zend\Filter\DateTimeFormatter();

$filter->setFormat('G:i, j.m.Y');

?>
<div class="row">
    <div class="col-md-6 mt-3">

        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formRow($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('body')); ?>
        </div>

        <div class="form-group">
            <?= $this->formRow($form->get('submit')); ?>
        </div>

        <?= $this->form()->closeTag($form); ?>

        <?php
        foreach ($messages as $message): ?>

            <div class="alert alert-secondary mb-1"  role="alert">
                <?= nl2br($this->escapeHtml($message->getBody())) ?>
            </div>

            <p class="mb-4 text-right text-secondary font-weight-light">
                <?= 'Отправил ' . $this->escapeHtml($message->getEmail()) . ' в ' . $filter->filter($message->getDateCreated()) ?>
            </p>


        <?php
        endforeach; ?>

    </div>
</div>
